"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['App.py']
APP_NAME = "SurfCompTimer"
DATA_FILES = ['config.ini', 'logs.log', 'surfer.icns', 'whale.ico',
              ('audio', ['audio/starting_sound.mp3',
                         'audio/finish_sound.mp3',
                         'audio/warning_sound.mp3'])
              ]
OPTIONS = {
    'argv_emulation': False,
    'includes': {'just_playback'},
    'packages': {'cffi'},
    'iconfile': 'surfer.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Timing Surf Competitions",
        # 'CFBundleIdentifier': "com.dlobb.osx.surfcomptimer",
        'CFBundleVersion': "1.0.1",
        'CFBundleShortVersionString': "1.0.1",
        'NSHumanReadableCopyright': u"Copyright © 2023, Denis Lobb, All Rights Reserved"
    }
}

setup(
app=APP,
data_files=DATA_FILES,
options={'py2app': OPTIONS},
setup_requires=['py2app'],
)

